# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  # using major version aliases
  - 7.0

before_script:
  - composer self-update
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer config repositories.mikewazovzky vcs https://github.com/mikewazovzky/demopackage.git
  - composer require mikewazovzky/demopackage dev-master
  - composer require satooshi/php-coveralls ^1.0
  # - composer update
  - cp ./vendor/mikewazovzky/demopackage/tests/config/.env ./
  - rm ./config/app.php
  - cp ./vendor/mikewazovzky/demopackage/tests/config/app.php ./config
  # - mysql -e "create database IF NOT EXISTS test;" -uroot
  # - php artisan migrate
  - mkdir -p build/logs  
  - cd ./vendor/mikewazovzky/demopackage

script:
  - ../../../vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
- travis_retry php vendor/bin/coveralls